version: "3.9"
services:
  api:
    build:
      context: ./api
      dockerfile: ./Dockerfile
    ports:
      - "4000:4000"
    environment:
      PGDATABASE: $PG_DATABASE
      PGUSER: $PG_USER
      PGPASSWORD: $PG_PASSWORD
      PGPORT: 5432
      PGHOST: db
    depends_on:
      - db
  db:
    image: "postgres:13"
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_DB: $PG_DATABASE
      POSTGRES_USER: $PG_USER
      POSTGRES_PASSWORD: $PG_PASSWORD
