version: "3.9"
services:
  db:
    image: "postgres:13"
    container_name: db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: $PG_DATABASE
      POSTGRES_USER: $PG_USER
      POSTGRES_PASSWORD: $PG_PASSWORD
